set search_path=bundle;
insert into bundle.trackable_nontable_relation (pk_column_id) values
-- (meta.column_id('meta','cast','id')),
(meta.column_id('meta','column','id')),
-- (meta.column_id('meta','connection','id')),
(meta.column_id('meta','constraint_check','id')),
(meta.column_id('meta','constraint_unique','id')),
-- (meta.column_id('meta','extension','id')),
(meta.column_id('meta','foreign_column','id')),
(meta.column_id('meta','foreign_data_wrapper','id')),
(meta.column_id('meta','foreign_key','id')),
(meta.column_id('meta','foreign_server','id')),
(meta.column_id('meta','foreign_table','id')),
(meta.column_id('meta','function','id')),
(meta.column_id('meta','function_parameter','id')),
(meta.column_id('meta','operator','id')),
-- (meta.column_id('meta','policy','id')),
-- (meta.column_id('meta','policy_role','id')),
(meta.column_id('meta','relation','id')),
(meta.column_id('meta','relation_column','id')),
-- (meta.column_id('meta','role','id')),
-- (meta.column_id('meta','role_inheritance','id')),
(meta.column_id('meta','schema','id')),
(meta.column_id('meta','sequence','id')),
(meta.column_id('meta','table','id')),
-- (meta.column_id('meta','table_privilege','id')),
(meta.column_id('meta','trigger','id')),
-- (meta.column_id('meta','type','id')),
(meta.column_id('meta','view','id'));
