create extension if not exists hstore schema public;
create extension if not exists dblink schema public;
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto schema public;
create extension if not exists postgres_fdw;
create extension meta;
create extension meta_triggers;
create extension bundle;
create extension event;
create extension endpoint;
create extension widget;
create extension semantics;
create extension ide;
create extension documentation;
